# Generated by Django 5.0.6 on 2024-05-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_care_system', '0002_shiiregyousha'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('patid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('patfname', models.CharField(max_length=64)),
                ('patlname', models.CharField(max_length=64)),
                ('hokenmei', models.CharField(max_length=64)),
                ('hokenexp', models.DateField()),
            ],
        ),
    ]
