# Generated by Django 5.0.6 on 2024-06-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_care_system', '0002_rename_medicine_id_treatment_medicineid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiiregyousha',
            name='shiiretel',
            field=models.CharField(max_length=64),
        ),
    ]
