# Generated by Django 5.0.6 on 2024-05-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_care_system', '0003_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('medicineid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('medicinename', models.CharField(max_length=64)),
                ('unit', models.CharField(max_length=8)),
            ],
        ),
    ]
