# Generated by Django 5.0.6 on 2024-06-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_care_system', '0003_alter_shiiregyousha_shiiretel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabyouin',
            fields=[
                ('tabyouinid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('tabyouinmei', models.CharField(max_length=64)),
                ('tabyouinaddress', models.CharField(max_length=64)),
                ('tabyouintel', models.CharField(max_length=64)),
                ('tabyouinshihonkin', models.IntegerField()),
                ('kyukyu', models.IntegerField()),
            ],
        ),
    ]
